-- Create roles and users required for this demo
USE ROLE USERADMIN;

-- Create role to work with data 
CREATE OR REPLACE ROLE ROL_DEMO_DATA_CRUD;
-- Create role & user for streamlit creator
CREATE OR REPLACE ROLE ROL_DEMO_STREAMLIT_CREATOR;
CREATE OR REPLACE USER DEMO_STREAMLIT_CREATOR WITH PASSWORD = '$up3r$ecr3tP@ssw0rd!'
DEFAULT_ROLE = ROL_DEMO_DATA_CRUD
DEFAULT_SECONDARY_ROLES = ('ALL');
-- Create role & user for streamlit viewer
CREATE OR REPLACE ROLE ROL_DEMO_STREAMLIT_VIEWER;
CREATE OR REPLACE USER DEMO_STREAMLIT_VIEWER WITH PASSWORD = '@n0th3rP@$$w0rd?'
DEFAULT_ROLE = ROL_DEMO_STREAMLIT_VIEWER
DEFAULT_SECONDARY_ROLES = ('ALL');

-- Create database, schema and warehouse
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS DEMO_PROGRAMMABLE_2024_STREAMLIT_DB;
CREATE SCHEMA IF NOT EXISTS DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.STREAMLIT_APP;
CREATE SCHEMA IF NOT EXISTS DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.DATA;
CREATE WAREHOUSE IF NOT EXISTS DEMO_PROGRAMMABLE_2024_STREAMLIT_WH WITH INITIALLY_SUSPENDED = TRUE;

-- Grant required privileges
USE ROLE SECURITYADMIN;

-- Grants to work with data
GRANT USAGE ON DATABASE DEMO_PROGRAMMABLE_2024_STREAMLIT_DB TO ROLE ROL_DEMO_DATA_CRUD;
GRANT USAGE ON SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.DATA TO ROLE ROL_DEMO_DATA_CRUD;
GRANT CREATE TABLE ON SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.DATA TO ROLE ROL_DEMO_DATA_CRUD;
GRANT CREATE VIEW ON SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.DATA TO ROLE ROL_DEMO_DATA_CRUD;
GRANT ALL ON FUTURE TABLES IN SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.DATA TO ROLE ROL_DEMO_DATA_CRUD;
GRANT ALL ON FUTURE VIEWS IN SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.DATA TO ROLE ROL_DEMO_DATA_CRUD;
GRANT USAGE ON WAREHOUSE DEMO_PROGRAMMABLE_2024_STREAMLIT_WH TO ROLE ROL_DEMO_DATA_CRUD;

-- Grants for streamlit viewer
GRANT ROLE ROL_DEMO_STREAMLIT_VIEWER TO USER DEMO_STREAMLIT_VIEWER;
GRANT USAGE ON DATABASE DEMO_PROGRAMMABLE_2024_STREAMLIT_DB TO ROLE ROL_DEMO_STREAMLIT_VIEWER;
GRANT USAGE ON SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.STREAMLIT_APP TO ROLE ROL_DEMO_STREAMLIT_VIEWER;

-- Additional grants for streamlit creator
GRANT ROLE ROL_DEMO_STREAMLIT_CREATOR TO USER DEMO_STREAMLIT_CREATOR;
GRANT ROLE ROL_DEMO_STREAMLIT_VIEWER TO ROLE ROL_DEMO_STREAMLIT_CREATOR;
GRANT CREATE STREAMLIT ON SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.STREAMLIT_APP TO ROLE ROL_DEMO_STREAMLIT_CREATOR;
GRANT CREATE STAGE ON SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.STREAMLIT_APP TO ROLE ROL_DEMO_STREAMLIT_CREATOR;
GRANT CREATE TABLE ON SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.STREAMLIT_APP TO ROLE ROL_DEMO_STREAMLIT_CREATOR;
GRANT USAGE ON WAREHOUSE DEMO_PROGRAMMABLE_2024_STREAMLIT_WH TO ROLE ROL_DEMO_STREAMLIT_CREATOR;

-- Grant streamlit creator access to data
GRANT ROLE ROL_DEMO_DATA_CRUD TO ROLE ROL_DEMO_STREAMLIT_CREATOR;

-- Grant privileges to create forecast model in Snowflake Cortex
GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA DEMO_PROGRAMMABLE_2024_STREAMLIT_DB.DATA TO ROLE ROL_DEMO_DATA_CRUD;

--For Step 06 later
--GRANT USAGE ON WAREHOUSE DEMO_PROGRAMMABLE_2024_STREAMLIT_WH TO ROLE ROL_DEMO_STREAMLIT_VIEWER;
