-- clean up database and all contents
USE ROLE SYSADMIN;
USE SECONDARY ROLE SYSADMIN;
DROP DATABASE IF EXISTS DEMO_PROGRAMMABLE_2024_STREAMLIT_DB;
DROP WAREHOUSE IF EXISTS DEMO_PROGRAMMABLE_2024_STREAMLIT_WH;

-- clean up users and roles
USE ROLE SECURITYADMIN;
USE SECONDARY ROLE SECURITYADMIN;
DROP USER IF EXISTS DEMO_STREAMLIT_CREATOR;
DROP USER IF EXISTS DEMO_STREAMLIT_VIEWER;
DROP ROLE IF EXISTS ROL_DEMO_STREAMLIT_CREATOR;
DROP ROLE IF EXISTS ROL_DEMO_STREAMLIT_VIEWER;
DROP ROLE IF EXISTS ROL_DEMO_DATA_CRUD;
